#!/usr/bin/env bash

set -euo pipefail

main() {
	echo "--- Installing the ECS CLI"
	local scratch="$(mktemp -d)"

	curl -sSL -o "${scratch}/ecs-cli" https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
	chmod +x "${scratch}/ecs-cli"

	export "PATH=${scratch}:${PATH}"

	ecs-cli --version

	echo "--- Configuring the ECS CLI"

	ecs-cli configure \
		--cluster "${ECS_CLUSTER}" \
		--default-launch-type FARGATE \
		--config-name buildkite

	echo "--- Deploy"
	ecs-cli compose \
		--project-name tutorial \
		service up \
		--create-log-groups \
		--cluster-config buildkite

	echo "--- Check Status"
	ecs-cli compose \
		--project-name tutorial \
		service ps \
		--cluster-config buildkite
}

main "$@"
